### ISSUE TITLE
Not able to get certificate with https://github.com/micromdm/scep test server

### ISSUE THREAD

**Issue by ravibajpai001** [scepman/scepclient#21]
If we try it with micromdm/scep . GetCACert and GetCACaps operation works fine. but PKIOperation fails with following error. 

failed pkcs7: cannot decrypt data: only RSA, DES, DES-EDE3, AES-256-CBC and AES-128-GCM supported.

Java client using jscep library workes fine with micromdm/scep server.

**Comment by bb-froggy** [comment]
I wonder what encryption algorithm micromdm/scep uses. If we had access to the SCEP response, we could check.

Can you wireshark the response? Or is it in micromdm's logs? Or did you build scepclient from scratch? If yes, you could add a line in scepclient.cs around line 451 and dump the "data" byte array into a file.

When you have the response, you can find the algorithm in the ASN.1 structure. Under Windows, you could use "certutil -asn" to see the ASN.1 structure. I can also do it for you if you send me the the SCEP response.

**Comment by ravibajpai001** [comment]
scep server returns null data with 500 Internal server error. this decrypt error we see in server logs. I checked server code . it fails at verify operation.
https://github.com/micromdm/scep/blob/main/scep/scep.go#L250

**Comment by bb-froggy** [comment]
So, does MicroMdm fail to decrypt the SCEP request or does SCEPclient fail to decrypt the SCEP response? I first thought that is was the latter case, but now I understand it is the former.

A SCEP request is a Signed PKCS#7, which is an outer package. Inside, there is an enveloped (=encrypted) PKCS#7. And inside this is a PKCS#10 CSR.

SCEPclient also uses Bouncy Castle to create the encrypted part of the SCEP Request. The encryption uses AES-256-CBC, which is in the list in your original message.

However, Line 250 in micromdm's scep.go is where it verifies the signed PKCS#7 as far as I can see. At that point, it doesn't even have access to the encrypted portion. The error message says that it cannot decrypt the PKCS#7 and mentiones a number of encryption algorithms, but they are not used for signing. This doesn't fit together. Are you sure that it is the verify operation that fails? And then the decrypt error message?

**Comment by ravibajpai001** [comment]
Thanks @bb-froggy.

I got the issue, the confusion happened because of the error mesage used in pkcs7 librray of go which is used by micromdm/scep server. they are using same error message in case of decrypt and verify function for algo.
https://github.com/fullsailor/pkcs7/blob/d7302db945fa/pkcs7.go#L307C25-L307C48

For signing if we provide sha256 instead of md5 as digest algo , it worked fine.
